# Generated by Django 6.0.4 on 2026-04-10 04:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, verbose_name="Сопроводительное письмо"
                    ),
                ),
                (
                    "resume_version",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="application_resumes/",
                        verbose_name="Резюме для этой заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewed", "Просмотрено"),
                            ("invited", "Приглашение на собеседование"),
                            ("rejected", "Отказ"),
                            ("accepted", "Принят"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название организации"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email для связи"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employers/",
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работодатель",
                "verbose_name_plural": "Работодатели",
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Дата и время собеседования"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Место проведения (или ссылка)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, verbose_name="Онлайн собеседование"
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="jobs.application",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собеседование",
                "verbose_name_plural": "Собеседования",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty", models.CharField(max_length=200, verbose_name="Факультет")),
                (
                    "year_of_study",
                    models.IntegerField(
                        choices=[
                            (1, "1 курс"),
                            (2, "2 курс"),
                            (3, "3 курс"),
                            (4, "4 курс"),
                            (5, "5 курс"),
                            (6, "Магистратура"),
                        ],
                        verbose_name="Курс",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx", "doc"]
                            )
                        ],
                        verbose_name="Резюме",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "subscribe_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Подписка на новые вакансии"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
            },
        ),
        migrations.CreateModel(
            name="ReviewStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Оценка (1-5)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_student",
                        to="jobs.employer",
                        verbose_name="Работодатель",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_employer_given",
                        to="jobs.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о студенте",
                "verbose_name_plural": "Отзывы о студентах",
            },
        ),
        migrations.CreateModel(
            name="ReviewEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Оценка (1-5)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="jobs.employer",
                        verbose_name="Работодатель",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_employer",
                        to="jobs.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о работодателе",
                "verbose_name_plural": "Отзывы о работодателях",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Изменение статуса заявки"),
                            ("new_vacancy", "Новая вакансия"),
                            ("interview_reminder", "Напоминание о собеседовании"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="jobs.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.studentprofile",
                verbose_name="Студент",
            ),
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("requirements", models.TextField(verbose_name="Требования")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Полная занятость"),
                            ("part_time", "Частичная занятость"),
                            ("internship", "Стажировка"),
                            ("remote", "Удалённая работа"),
                        ],
                        max_length=20,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Зарплата от"
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Зарплата до"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Место работы"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("closed", "Закрыта"),
                            ("draft", "Черновик"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="jobs.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="jobs.employer",
                        verbose_name="Работодатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.vacancy",
                verbose_name="Вакансия",
            ),
        ),
        migrations.CreateModel(
            name="SavedVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сохранения"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_vacancies",
                        to="jobs.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранная вакансия",
                "verbose_name_plural": "Избранные вакансии",
                "unique_together": {("student", "vacancy")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("student", "vacancy")},
        ),
    ]
